FROM python
WORKDIR /app

COPY . /app/

CMD ["python", "rng.py"]






# ➜  docker run -i b8 
# Please enter the min number: 1
# Please enter the max number: 2
# 2

# ➜  docker start -ia 55fb2e390f16
# Please enter the min number: 1
# Please enter the max number: 2
# 2










